# Generates build information for LaTeX
#
# @author Connor Henley, @thatging3rkid
import datetime
import subprocess

def main():
    # first, print some debugging infro
    print("%%% buildinfo.tex\n%%%\n%%% Generated by gen_buildinfo.py on " + str(datetime.datetime.now()) + "\n")

    # next, get the current git state
    git_describe = "*error\\_getting\\_version*"
    git_branch = "*branch\\_error*"
    try:
        git_describe = subprocess.check_output(["git", "describe", "--tags", "--long"]).strip().decode("utf-8")
        git_branch = subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).strip().decode("utf-8")
    except:
        pass

    # finally, print the footers
    footer = "version: \\texttt{"+ git_describe +"}";
    if git_branch != "master":
        footer += " on branch \\texttt{"+ git_branch +"}"
    print("\\lfoot{" + footer + "}")

if __name__ == "__main__":
    main()
