# constitution GitHub Action config
#
# Action that runs on every push
#     - builds the document and generates a PDF
#     - uploads the resulting PDF as an artifact
#
# @version v1.0.2
# @author Connor Henley, @thatging3rkid
name: "Build PDF"

runs:
  using: 'node16'  # use latest LTS version of NodeJS for GitHub actions (like checkout)

on:
  # run on a push to every branch but master
  push:
    branches-ignore:
      - 'master'

  # run on every new release (only once)
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-22.04  # this has been tested to work with Ubuntu 22.04, some day it will need to be updated!

    steps:
      # checkout the repository (pull master on release)
      - uses: actions/checkout@v2
        if: github.event_name == 'release'
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}
          
      # checkout the repository
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
      
      # get more git history
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # fetch all tags
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/* # fetch all branches
      - run: git fetch --prune --unshallow # fetch history for tags and branches

      # install required packages
      - name: Configure
        run: ./configure

      # build the PDF
      - name: Build
        run: make constitution.pdf

      # upload the resulting PDF
      - uses: actions/upload-artifact@v1
        with:
          name: constitution
          path: constitution.pdf
